# Generated by Django 4.2.1 on 2023-05-26 21:47

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='Nome de usuário')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('telefone', models.CharField(max_length=12, verbose_name='Telefone')),
                ('is_staff', models.BooleanField(default=True, verbose_name='Funcionário')),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', core.models.UsuarioManager()),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Cargo_nome', max_length=30)),
                ('salario', models.FloatField()),
                ('carga_horaria', models.IntegerField(choices=[(20, '20h'), (40, '40h')], default=40)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Depto_nome', max_length=50)),
                ('sigla', models.CharField(default='', max_length=10)),
                ('data_criacao', models.DateField(default='2000-01-01')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cpf', models.CharField(default='00000000000', max_length=11, unique=True)),
                ('sexo', models.CharField(max_length=1)),
                ('data_nasc', models.DateField(default='YYYY-DD-MM')),
                ('cod_cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.cargo')),
                ('cod_depto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.departamento')),
                ('cod_func', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('cod_gerente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('Seg', 'Segunda-Feira'), ('Ter', 'Terça-Feira'), ('Qua', 'Quarta-Feira'), ('Qui', 'Quinta-Feira'), ('Sex', 'Sexta-Feira'), ('Sab', 'Sábado'), ('Dom', 'Domingo')], default='Seg', max_length=10)),
                ('hora_entrada', models.CharField(default='0h', max_length=12)),
                ('hora_saida', models.CharField(default='24h', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(default='Turno', max_length=10, unique=True)),
                ('hora_inicio', models.CharField(default='00', max_length=12)),
                ('hora_fim', models.CharField(default='00', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Ponto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(default='', max_length=255)),
                ('data_marcacao', models.DateField(default='2000-01-01')),
                ('cod_func', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.funcionario')),
                ('cor_turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.turno')),
            ],
        ),
        migrations.AddField(
            model_name='funcionario',
            name='cod_horario',
            field=models.ManyToManyField(to='core.horario'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='cod_turno',
            field=models.ManyToManyField(to='core.turno'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='cod_gerente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.funcionario'),
        ),
    ]
