# Generated by Django 4.2.1 on 2023-05-16 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Cargo_nome', max_length=30)),
                ('salario', models.FloatField()),
                ('carga_horaria', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Depto_nome', max_length=50)),
                ('sigla', models.CharField(default='', max_length=10)),
                ('data_criacao', models.DateField(default='2000-01-01')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='nome', max_length=100)),
                ('cpf', models.CharField(default='cpf', max_length=11, unique=True)),
                ('sexo', models.CharField(max_length=1)),
                ('data_nasc', models.DateField(default='2000-01-01')),
                ('cod_cargo', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.cargo')),
                ('cod_depto', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.departamento')),
                ('cod_gerente', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(default='24h', max_length=10)),
                ('hora_entrada', models.CharField(default='0h', max_length=12)),
                ('hora_saida', models.CharField(default='24h', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(default='Turno', max_length=10, unique=True)),
                ('hora_inicio', models.CharField(default='00', max_length=12)),
                ('hora_fim', models.CharField(default='00', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(default='user', max_length=11, unique=True)),
                ('email', models.CharField(default='email', max_length=30, unique=True)),
                ('senha', models.CharField(default='password', max_length=12)),
                ('token', models.CharField(default='0000', max_length=12, unique=True)),
                ('cod_func', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='Ponto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(default='', max_length=255)),
                ('data', models.DateField(default='2000-01-01')),
                ('cod_func', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.funcionario')),
                ('cor_turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.turno')),
            ],
        ),
        migrations.AddField(
            model_name='departamento',
            name='cod_gerente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.funcionario'),
        ),
    ]
