# Generated by Django 4.2.1 on 2023-05-16 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_funcionario_cod_cargo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cod_depto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.departamento'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cod_gerente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.funcionario'),
        ),
    ]
