# Generated by Django 4.2.1 on 2023-05-16 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_funcionario_cod_depto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cod_func',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.funcionario'),
        ),
    ]
