# Generated by Django 4.2.1 on 2023-05-16 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_usuario_cod_func'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='data_nasc',
            field=models.DateField(default='YYYY-DD-MM'),
        ),
    ]
