# Generated by Django 4.2.1 on 2023-05-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_funcionario_data_nasc'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='cod_horario',
            field=models.ManyToManyField(to='core.horario'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='cod_turno',
            field=models.ManyToManyField(to='core.turno'),
        ),
    ]
