# Generated by Django 4.2.1 on 2023-05-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_funcionario_cod_horario_funcionario_cod_turno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ponto',
            old_name='data',
            new_name='data_marcacao',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='token',
            field=models.CharField(default='0000', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuario',
            field=models.CharField(default='user', max_length=20, unique=True),
        ),
    ]
