# Generated by Django 4.2.1 on 2023-05-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_cargo_carga_horaria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(default='00000000000', max_length=11, unique=True),
        ),
    ]
